[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pipo"
version = "0.0.1"
authors = [
  { name="Gemini", email="gemini@google.com" },
]
description = "A modern tool to generate requirements.txt for a Python project."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pyfiglet",
    "colorama",
    "safety",
    "bandit",
    "stdlib-list",
]

[project.scripts]
pipo = "pipo.main:main"
