import os
import ast
import argparse
import sys
import importlib.metadata
import subprocess # nosec: Subprocess calls are used with controlled inputs, mitigating risks.
from pyfiglet import Figlet
from colorama import Fore, Style, init

def get_std_libs():
    """Fetches the list of standard library modules for the current Python version."""
    # In a real-world scenario, we might use a pre-compiled list for a specific Python version
    # or use more sophisticated methods. For this tool, we'll use a known list.
    # This list is for Python 3.10. A more robust tool would adjust this based on the Python version.
    try:
        from stdlib_list import stdlib_list
        return set(stdlib_list("3.10"))
    except ImportError:
        print("Warning: 'stdlib-list' not found. Falling back to a basic list. Please run 'pip install stdlib-list' for better accuracy.", file=sys.stderr)
        # A fallback list if stdlib_list is not available
        return {
            "os", "sys", "ast", "argparse", "time", "datetime", "math", "random", "json",
            "re", "subprocess", "collections", "functools", "itertools", "pathlib", "socket",
            "select", "string", "traceback", "unittest", "urllib", "logging", "threading", "importlib"
            # This is not exhaustive and is a limitation of the fallback.
        }


def find_imports(path):
    """Find all imported modules in a given Python file using AST."""
    imports = set()
    try:
        with open(path, 'r', encoding='utf-8') as f:
            tree = ast.parse(f.read(), filename=path)
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    # Get the top-level module (e.g., 'os.path' -> 'os')
                    imports.add(alias.name.split('.')[0])
            elif isinstance(node, ast.ImportFrom):
                # Ignore relative imports (e.g., from . import foo)
                if node.level > 0:
                    continue
                if node.module:
                    imports.add(node.module.split('.')[0])
    except Exception as e:
        print(f"Error parsing {path}: {e}", file=sys.stderr)
    return imports



def _uninstall_pipo():
    """Uninstalls the pipo tool."""
    print(f"{Fore.CYAN}Uninstalling pipo...{Style.RESET_ALL}")
    try:
        subprocess.run([sys.executable, "-m", "pip", "uninstall", "pipo", "-y"], check=True) # nosec
        print(f"{Fore.GREEN}pipo uninstalled successfully!{Style.RESET_ALL}\n")
        print(f"{Fore.YELLOW}Note: If pipo was installed in editable mode, its directory still exists.{Style.RESET_ALL}")
    except KeyboardInterrupt:
        print(f"\n{Fore.YELLOW}Operation cancelled by user.{Style.RESET_ALL}")
        sys.exit(0)
    except subprocess.CalledProcessError as e:
        print(f"{Fore.RED}Error during uninstallation: {e}{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"{Fore.RED}An unexpected error occurred: {e}{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)

def _dockerize_project(args): # args parameter used directly
    """Generates a Dockerfile for the project."""
    path = os.path.abspath(args.path)
    if not os.path.isdir(path):
        print(f"{Fore.RED}Error: Path '{path}' is not a valid directory.{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)

    app_type = args.app_type
    main_file = args.main_file
    port = args.port

    # Basic Dockerfile content
    dockerfile_content = f"""
# Use the official Python image as a base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy requirements.txt and install dependencies
# Note: Pipo expects requirements.txt to be already generated by 'pipo scan'
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port the application uses
EXPOSE {port}
"""
    # Customize CMD based on app_type
    if app_type == 'flask':
        # Assumes the Flask app object is named 'app' in the main_file
        # main_file 'app.py' becomes 'app' module
        dockerfile_content += f'\n# Command to run the Flask application with Gunicorn\nCMD ["gunicorn", "--bind", "0.0.0.0:{port}", "{main_file.replace(".py", "")}:app"]'
    elif app_type == 'django': # Placeholder, more complex normally
        # Assumes standard Django project structure and wsgi.py
        dockerfile_content += f'\n# Command to run the Django application with Gunicorn\nCMD ["gunicorn", "--bind", "0.0.0.0:{port}", "{main_file.replace(".py", "")}.wsgi:application"]'
    elif app_type == 'script':
        dockerfile_content += f'\n# Command to run the Python script\nCMD ["python", "{main_file}"]'
    else: # Fallback to generic simple script command
        print(f"{Fore.YELLOW}Warning: Unknown app_type '{app_type}'. Using generic Python script command.{Style.RESET_ALL}", file=sys.stderr)
        dockerfile_content += f'\n# Command to run the Python application (generic fallback)\nCMD ["python", "{main_file}"]'


    output_path = os.path.join(path, f'Dockerfile')
    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(dockerfile_content)
        print(f"{Fore.GREEN}Dockerfile successfully generated at {output_path}{Style.RESET_ALL}")
    except IOError as e:
        print(f"{Fore.RED}Error writing Dockerfile to {output_path}: {e}{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)

def run_scan_command(args): # Scan logic extracted to a function
    """Scans a project for imports and generates requirements.txt."""
    project_path = os.path.abspath(args.path)
    if not os.path.isdir(project_path):
        print(f"{Fore.RED}Error: Path '{project_path}' is not a valid directory.{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)

    print(f"{Fore.CYAN}Scanning project at: {project_path}{Style.RESET_ALL}")

    all_imports = set()
    for root, _, files in os.walk(project_path):
        # A simple way to exclude common virtual environment folders
        if 'venv' in root or 'env' in root or '.git' in root or '__pycache__' in root:
            continue
        for file in files:
            if file.endswith('.py'):
                file_path = os.path.join(root, file)
                all_imports.update(find_imports(file_path))

    std_libs = get_std_libs()
    external_imports = sorted(list(all_imports - std_libs))

    output_path = os.path.join(project_path, 'requirements.txt')
    print(f"Found {len(external_imports)} external dependencies.")

    if not external_imports:
        print("No external dependencies found. Nothing to write.")
        # If no requirements.txt is needed, ensure we don't accidentally create an empty one
        if os.path.exists(output_path):
            os.remove(output_path) # Clean up existing empty requirements.txt if present
            print(f"Removed empty requirements.txt at {output_path}")
        return

    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            for lib in external_imports:
                f.write(f"{lib}\\n")
        print(f"{Fore.GREEN}Successfully wrote requirements.txt to {output_path}{Style.RESET_ALL}")
    except IOError as e:
        print(f"{Fore.RED}Error writing to {output_path}: {e}{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)



def _init_ci(args):
    """Generates a basic CI/CD configuration file."""
    project_path = os.path.abspath(args.path)
    if not os.path.isdir(project_path):
        print(f"{Fore.RED}Error: Path '{project_path}' is not a valid directory.{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)

    platform = args.platform.lower()
    output_dir = os.path.join(project_path, '.github', 'workflows')
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, 'ci.yml')

    ci_content = ""
    if platform == 'github-actions':
        ci_content = f"""name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run tests
        run: pipo test .

      - name: Build Docker image
        if: {args.push_docker_image}
        run: pipo dockerize . --docker-image-name {args.docker_image_name}

      - name: Log in to Docker Hub
        if: {args.push_docker_image}
        uses: docker/login-action@v1
        with:
          username: ${{{{ secrets.DOCKER_USERNAME }}}}
          password: ${{{{ secrets.DOCKER_PASSWORD }}}}

      - name: Push Docker image
        if: {args.push_docker_image}
        run: docker push {args.docker_image_name}
"""
    else:
        print(f"{Fore.RED}Error: CI platform '{platform}' not supported yet.{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)

    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(ci_content)
        print(f"{Fore.GREEN}CI configuration for {platform} successfully generated at {output_path}{Style.RESET_ALL}")
    except IOError as e:
        print(f"{Fore.RED}Error writing CI configuration to {output_path}: {e}{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)


def _generate_kube_manifests(args):
    """Generates Kubernetes deployment, service, and optionally Ingress YAML files interactively or from arguments."""
    project_path = os.path.abspath(args.path)
    if not os.path.isdir(project_path):
        print(f"{Fore.RED}Error: Path '{project_path}' is not a valid directory.{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)

    try:
        # --- Get Image Name ---
        image = args.image
        if not image:
            image = input(f"{Fore.CYAN}Enter Docker image name (e.g., your-docker-username/your-app:v1): {Style.RESET_ALL}").strip()
            if not image:
                print(f"{Fore.RED}Nama image tidak boleh kosong.{Style.RESET_ALL}", file=sys.stderr)
                sys.exit(1)

        # --- Get App Name ---
        app_name = args.app_name
        if not app_name:
            try:
                app_name = image.split('/')[-1].split(':')[0]
            except IndexError:
                app_name = 'my-app'
            app_name = input(f"{Fore.CYAN}Enter application name (default: {app_name}): {Style.RESET_ALL}").strip() or app_name

        # --- Get Port ---
        port = args.port
        if not port:
            while True:
                port_str = input(f"{Fore.CYAN}Enter application container port (default: 8080): {Style.RESET_ALL}").strip()
                if not port_str:
                    port = 8080
                    break
                try:
                    port = int(port_str)
                    break
                except ValueError:
                    print(f"{Fore.RED}Port harus berupa angka.{Style.RESET_ALL}", file=sys.stderr)

        # --- Get Service Type ---
        service_type = args.service_type
        valid_service_types = ['NodePort', 'LoadBalancer', 'ClusterIP']
        if not service_type:
            while True:
                service_type = input(f"{Fore.CYAN}Select Service type (NodePort, LoadBalancer, ClusterIP) (default: NodePort): {Style.RESET_ALL}").strip()
                if not service_type:
                    service_type = 'NodePort'
                    break
                if service_type in valid_service_types:
                    break
                else:
                    print(f"{Fore.RED}Tipe Service tidak valid. Pilih salah satu dari: {', '.join(valid_service_types)}{Style.RESET_ALL}", file=sys.stderr)

        # --- Get Namespace ---
        namespace = args.namespace
        if not namespace:
            namespace = input(f"{Fore.CYAN}Enter Kubernetes Namespace (default: default): {Style.RESET_ALL}").strip() or 'default'

        # --- Get Ingress details if requested ---
        generate_ingress = args.ingress
        ingress_host = args.host
        ingress_path = args.path_ingress # Renamed to avoid conflict with project path
        ingress_class = args.ingress_class

        if not generate_ingress:
            generate_ingress_str = input(f"{Fore.CYAN}Do you want to generate Ingress YAML? (y/N): {Style.RESET_ALL}").strip().lower()
            generate_ingress = (generate_ingress_str == 'y')

        if generate_ingress:
            if not ingress_host:
                ingress_host = input(f"{Fore.CYAN}Enter Ingress hostname (e.g., your-app.example.com): {Style.RESET_ALL}").strip()
                if not ingress_host:
                    print(f"{Fore.RED}Hostname untuk Ingress tidak boleh kosong jika Ingress dibuat.{Style.RESET_ALL}", file=sys.stderr)
                    sys.exit(1)
            if not ingress_path:
                ingress_path = input(f"{Fore.CYAN}Enter Ingress path (default: /): {Style.RESET_ALL}").strip() or '/'
            if not ingress_class:
                ingress_class = input(f"{Fore.CYAN}Enter Ingress Class (optional, default: nginx): {Style.RESET_ALL}").strip() or 'nginx'
    except KeyboardInterrupt:
        print(f"\n{Fore.YELLOW}Operation cancelled by user.{Style.RESET_ALL}")
        sys.exit(0)


    # --- Deployment YAML ---
    deployment_yaml = f"""
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {app_name}-deployment
  namespace: {namespace}
  labels:
    app: {app_name}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {app_name}
  template:
    metadata:
      labels:
        app: {app_name}
    spec:
      containers:
      - name: {app_name}
        image: {image}
        imagePullPolicy: Always
        ports:
        - containerPort: {port}
"""

    # --- Service YAML ---
    service_yaml = f"""
apiVersion: v1
kind: Service
metadata:
  name: {app_name}-service
  namespace: {namespace}
spec:
  selector:
    app: {app_name}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {port}
  type: {service_type}
"""

    # --- Ingress YAML (Optional) ---
    ingress_yaml = ""
    if generate_ingress:
        ingress_yaml = f"""
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {app_name}-ingress
  namespace: {namespace}
  annotations:
    kubernetes.io/ingress.class: {ingress_class}
spec:
  rules:
  - host: {ingress_host}
    http:
      paths:
      - path: {ingress_path}
        pathType: Prefix
        backend:
          service:
            name: {app_name}-service
            port:
              number: 80
"""


    deployment_output_path = os.path.join(project_path, 'deployment.yaml')
    service_output_path = os.path.join(project_path, 'service.yaml')
    ingress_output_path = os.path.join(project_path, 'ingress.yaml')

    try:
        with open(deployment_output_path, 'w', encoding='utf-8') as f:
            f.write(deployment_yaml)
        print(f"{Fore.GREEN}Deployment YAML successfully generated at {deployment_output_path}{Style.RESET_ALL}")

        with open(service_output_path, 'w', encoding='utf-8') as f:
            f.write(service_yaml)
        print(f"{Fore.GREEN}Service YAML successfully generated at {service_output_path}{Style.RESET_ALL}")

        if generate_ingress:
            with open(ingress_output_path, 'w', encoding='utf-8') as f:
                f.write(ingress_yaml)
            print(f"{Fore.GREEN}Ingress YAML successfully generated at {ingress_output_path}{Style.RESET_ALL}")

    except IOError as e:
        print(f"{Fore.RED}Error writing YAML file: {e}{Style.RESET_ALL}", file=sys.stderr)



def _security_scan(args):
    """Performs a security scan on requirements.txt using the safety tool."""
    project_path = os.path.abspath(args.path)
    if not os.path.isdir(project_path):
        print(f"{Fore.RED}Error: Path '{project_path}' is not a valid directory.{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)

    requirements_path = os.path.join(project_path, 'requirements.txt')
    if not os.path.exists(requirements_path):
        print(f"{Fore.YELLOW}Warning: requirements.txt not found at {requirements_path}. Running 'pipo scan' first...{Style.RESET_ALL}")
        # Temporarily create a dummy args object for run_scan_command
        class DummyArgs:
            def __init__(self, path):
                self.path = path
        run_scan_command(DummyArgs(project_path))
        if not os.path.exists(requirements_path):
            print(f"{Fore.RED}Error: requirements.txt could not be generated. Aborting security scan.{Style.RESET_ALL}", file=sys.stderr)
            sys.exit(1)

    print(f"{Fore.CYAN}Performing security scan on {requirements_path} with Safety...{Style.RESET_ALL}")
    try:
        # Safety check command
        result = subprocess.run([sys.executable, "-m", "safety", "check", "-r", requirements_path], capture_output=True, text=True, check=True) # nosec
        print(result.stdout)
        print(f"{Fore.GREEN}Security scan completed. No known vulnerabilities found!{Style.RESET_ALL}")
    except KeyboardInterrupt:
        print(f"\n{Fore.YELLOW}Operation cancelled by user.{Style.RESET_ALL}")
        sys.exit(0)
    except subprocess.CalledProcessError as e:
        print(f"{Fore.RED}Security scan found vulnerabilities or failed: {e}{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)
    except FileNotFoundError:
        print(f"{Fore.RED}Error: 'safety' command not found. Please ensure it's installed (`pip install safety`).{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"{Fore.RED}An unexpected error occurred during security scan: {e}{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)

def _generate_helm_chart(args):
    """Generates a basic Helm chart structure."""
    chart_path = os.path.abspath(os.path.join(args.path, args.chart_name))
    templates_path = os.path.join(chart_path, 'templates')

    if os.path.exists(chart_path):
        print(f"{Fore.RED}Error: Chart directory '{chart_path}' already exists. Aborting.{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)

    print(f"{Fore.CYAN}Generating Helm chart structure at {chart_path}...{Style.RESET_ALL}")

    try:
        os.makedirs(templates_path, exist_ok=True)

        # Chart.yaml
        chart_yaml_content = f"""
apiVersion: v2
name: {args.chart_name}
description: A Helm chart for a Python application generated by Pipo

# A chart can be either an application or a library chart.
#
# Application charts are a collection of templates that can be deployed by Helm.
# Library charts provide useful utilities or functions for the chart writer.
# As a best practice, some running apps should be in a separate application chart.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.16.0 # Replace with your application's version
"""

        with open(os.path.join(chart_path, 'Chart.yaml'), 'w') as f:
            f.write(chart_yaml_content)

        # values.yaml
        values_yaml_content = f"""
# Default values for {args.chart_name}.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: your-docker-username/your-app
  pullPolicy: IfNotPresent # Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.16.0" # Replace with your application's image tag

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  className: "nginx"
  annotations: {{}}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific # Prefix

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {{}}
  # The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {{}}

podSecurityContext: {{}}
  # fsGroup: 2000

securityContext: {{}}
  # capabilities:
  #   drop:
  #     - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {{}}
  # We usually recommend not to specify default resources for production workloads.
  # Instead, users should configure them based on their usage.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {{}}

tolerations: []

affinity: {{}}
"""
        with open(os.path.join(chart_path, 'values.yaml'), 'w') as f:
            f.write(values_yaml_content)

        # Basic templates (can be enriched later with actual Helm templating)
        with open(os.path.join(templates_path, 'deployment.yaml'), 'w') as f:
            f.write("""
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "{{ .Chart.Name | lower }}".fullname . }}
  labels:
    {{- include "{{ .Chart.Name | lower }}".labels . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "{{ .Chart.Name | lower }}".selectorLabels . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "{{ .Chart.Name | lower }}".selectorLabels . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "{{ .Chart.Name | lower }}".serviceAccountName . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name | lower }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
"""
            )
        with open(os.path.join(templates_path, 'service.yaml'), 'w') as f:
            f.write("""
apiVersion: v1
kind: Service
metadata:
  name: {{ include "{{ .Chart.Name | lower }}".fullname . }}
  labels:
    {{- include "{{ .Chart.Name | lower }}".labels . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "{{ .Chart.Name | lower }}".selectorLabels . | nindent 4 }}"""
            )
        with open(os.path.join(templates_path, 'ingress.yaml'), 'w') as f:
            f.write("""
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "{{ .Chart.Name | lower }}".fullname . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "{{ .Chart.Name | lower }}".labels . | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "{{ .Chart.Name | lower }}".fullname . }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}"""
            )
        # Add _helpers.tpl for common labels and names
        with open(os.path.join(templates_path, '_helpers.tpl'), 'w') as f:
            f.write("""
{{/* vim: set filetype=helm: */}}

{{/*
Expand the name of the chart.
*/}}
{{- define "{{ .Chart.Name | lower }}".name }}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "{{ .Chart.Name | lower }}".fullname }}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as a label
*/}}
{{- define "{{ .Chart.Name | lower }}".chart }}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "{{ .Chart.Name | lower }}".labels }}
helm.sh/chart: {{ include "{{ .Chart.Name | lower }}".chart . }}
{{ include "{{ .Chart.Name | lower }}".selectorLabels . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "{{ .Chart.Name | lower }}".selectorLabels }}
app.kubernetes.io/name: {{ include "{{ .Chart.Name | lower }}".name . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "{{ .Chart.Name | lower }}".serviceAccountName }}
{{- if .Values.serviceAccount.create }}
{{- default (include "{{ .Chart.Name | lower }}".fullname .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}
"""
            )

        print(f"{Fore.GREEN}Helm chart '{args.chart_name}' successfully generated at {chart_path}{Style.RESET_ALL}")
        print(f"{Fore.YELLOW}Remember to review and customize values.yaml and templates/*.yaml files.{Style.RESET_ALL}")
    except Exception as e:
        print(f"{Fore.RED}Error generating Helm chart: {e}{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)




        
        
        
        

def _sast_scan(args):
    """Performs a SAST scan on the project directory using the bandit tool."""
    project_path = os.path.abspath(args.path)
    if not os.path.isdir(project_path):
        print(f"{Fore.RED}Error: Path '{project_path}' is not a valid directory.{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)

    # Construct the path to the pipo directory
    pipo_path = os.path.join(project_path, 'pipo')

    print(f"{Fore.CYAN}Performing SAST scan on {pipo_path} with Bandit...{Style.RESET_ALL}")
    try:
        # Bandit scan command
        # -r for recursive, -f for output format (txt), -o for output file (stdout)
        result = subprocess.run([sys.executable, "-m", "bandit", "-r", pipo_path, "-f", "txt", "-o", "-"], capture_output=True, text=True, check=True) # nosec
        if result.stdout:
            print(f"{Fore.YELLOW}Bandit Scan Results:\n{result.stdout}{Style.RESET_ALL}")
        print(f"{Fore.GREEN}SAST scan completed. No issues found by Bandit!{Style.RESET_ALL}")
    except KeyboardInterrupt:
        print(f"\n{Fore.YELLOW}Operation cancelled by user.{Style.RESET_ALL}")
        sys.exit(0)
    except subprocess.CalledProcessError as e:
        print(f"{Fore.RED}SAST scan found issues or failed: {e}{Style.RESET_ALL}", file=sys.stderr)
        if e.stdout:
            print(f"{Fore.YELLOW}Bandit Scan Results:\n{e.stdout}{Style.RESET_ALL}")
        if e.stderr:
            print(f"{Fore.RED}Bandit Error:\n{e.stderr}{Style.RESET_ALL}")
        sys.exit(1)
    except FileNotFoundError:
        print(f"{Fore.RED}Error: 'bandit' command not found. Please ensure it's installed (`pip install bandit`).{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"{Fore.RED}An unexpected error occurred during SAST scan: {e}{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)

def _run_tests(args):
    """Runs tests using pytest."""
    print(f"{Fore.CYAN}Running tests...{Style.RESET_ALL}")
    try:
        result = subprocess.run([sys.executable, "-m", "pytest", args.path], check=True, capture_output=True, text=True) # nosec
        print(result.stdout)
        print(f"{Fore.GREEN}Tests completed successfully!{Style.RESET_ALL}")
    except KeyboardInterrupt:
        print(f"\n{Fore.YELLOW}Operation cancelled by user.{Style.RESET_ALL}")
        sys.exit(0)
    except subprocess.CalledProcessError as e:
        print(f"{Fore.RED}Tests failed:\n{e.stderr}{Style.RESET_ALL}", file=sys.stderr)
        raise e

def _generate_gitops_manifest(args):
    """Generates a basic GitOps manifest (e.g., Argo CD Application)."""
    project_path = os.path.abspath(args.path)
    if not os.path.isdir(project_path):
        print(f"{Fore.RED}Error: Path '{project_path}' is not a valid directory.{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)

    app_name = args.app_name
    repo_url = args.repo_url
    path_in_repo = args.path_in_repo
    target_revision = args.target_revision
    namespace = args.namespace
    tool = args.tool

    try:
        if not app_name:
            app_name = input(f"{Fore.CYAN}Enter application name (default: my-gitops-app): {Style.RESET_ALL}").strip() or 'my-gitops-app'
        if not repo_url:
            repo_url = input(f"{Fore.CYAN}Enter Git repository URL (e.g., https://github.com/your-org/your-repo.git): {Style.RESET_ALL}").strip()
            if not repo_url:
                print(f"{Fore.RED}Repository URL cannot be empty.{Style.RESET_ALL}", file=sys.stderr)
                sys.exit(1)
        if not path_in_repo:
            path_in_repo = input(f"{Fore.CYAN}Enter path within repository to Kubernetes manifests (default: '.'): {Style.RESET_ALL}").strip() or '.'
        if not target_revision:
            target_revision = input(f"{Fore.CYAN}Enter target Git revision (branch/tag/commit, default: HEAD): {Style.RESET_ALL}").strip() or 'HEAD'
        if not namespace:
            namespace = input(f"{Fore.CYAN}Enter Kubernetes Namespace for deployment (default: default): {Style.RESET_ALL}").strip() or 'default'
        if not tool:
            tool = input(f"{Fore.CYAN}Select GitOps tool (argocd, fluxcd) (default: argocd): {Style.RESET_ALL}").strip().lower() or 'argocd'
            if tool not in ['argocd', 'fluxcd']:
                print(f"{Fore.RED}Invalid GitOps tool selected. Must be 'argocd' or 'fluxcd'.{Style.RESET_ALL}", file=sys.stderr)
                sys.exit(1)
    except KeyboardInterrupt:
        print(f"\n{Fore.YELLOW}Operation cancelled by user.{Style.RESET_ALL}")
        sys.exit(0)

    gitops_manifest_content = ""
    output_filename = ""

    if tool == 'argocd':
        output_filename = f"argocd-application-{app_name}.yaml"
        gitops_manifest_content = f"""
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {app_name}
  namespace: argocd # Argo CD applications are typically managed in the argocd namespace
spec:
  destination:
    namespace: {namespace}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: {path_in_repo}
    repoURL: {repo_url}
    targetRevision: {target_revision}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
"""
    elif tool == 'fluxcd':
        output_filename = f"fluxcd-kustomization-{app_name}.yaml"
        gitops_manifest_content = f"""
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {app_name}
  namespace: flux-system # Flux CD Kustomizations are typically managed in the flux-system namespace
spec:
  interval: 10m
  path: {path_in_repo}
  prune: true
  sourceRef:
    kind: GitRepository
    name: {app_name}-source
  targetNamespace: {namespace}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: {app_name}-source
  namespace: flux-system
spec:
  interval: 1m
  url: {repo_url}
  ref:
    branch: {target_revision}
"""

    output_path = os.path.join(project_path, output_filename)

    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(gitops_manifest_content)
        print(f"{Fore.GREEN}GitOps manifest for {tool} successfully generated at {output_path}{Style.RESET_ALL}")
    except IOError as e:
        print(f"{Fore.RED}Error writing GitOps manifest to {output_path}: {e}{Style.RESET_ALL}", file=sys.stderr)
        sys.exit(1)


def main():
    """Main entry point for the pipo CLI tool."""
    init(autoreset=True) # Initialize Colorama

    try:
        version = importlib.metadata.version('pipo')
    except importlib.metadata.PackageNotFoundError:
        version = '0.0.1' # Fallback version if package is not installed

    # Generate and print banner with a modern aesthetic border
    banner_text = r"""
██████╗ ██╗██████╗  ██████╗
██╔══██╗██║██╔══██╗██╔═══██╗
██████╔╝██║██████╔╝██║   ██║
██╔═══╝ ██║██╔═══╝ ██║   ██║
██║     ██║██║     ╚██████╔╝
╚═╝     ╚═╝╚═╝      ╚═════╝"""
    description_text = "A modern tool to generate requirements.txt for a Python project."
    version_text = f"Version: {version}"

    # Calculate max width for consistent border
    max_banner_line_len = max(len(line) for line in banner_text.split('\n') if line)
    max_content_width = max(max_banner_line_len, len(description_text), len(version_text)) + 4 # +4 for internal padding

    # Border characters
    horizontal_char = '═'
    vertical_char = '║'
    top_left = '╔'
    top_right = '╗'
    bottom_left = '╚'
    bottom_right = '╝'

    # Print top border
    print(f"{top_left}{horizontal_char * (max_content_width + 2)}{top_right}")

    # Print colored banner lines
    colors = [Fore.RED, Fore.YELLOW, Fore.GREEN, Fore.CYAN, Fore.BLUE, Fore.MAGENTA]
    for i, line in enumerate(banner_text.split('\n')):
        if line:
            padded_line = line.ljust(max_content_width)
            print(f"{vertical_char} {colors[i % len(colors)]}{padded_line}{Style.RESET_ALL} {vertical_char}")

    # Print separator
    print(f"{vertical_char}{horizontal_char * (max_content_width + 2)}{vertical_char}")

    # Print description
    padded_description = description_text.ljust(max_content_width)
    print(f"{vertical_char} {Fore.CYAN}{padded_description}{Style.RESET_ALL} {vertical_char}")

    # Print version
    padded_version = version_text.ljust(max_content_width)
    print(f"{vertical_char} {Fore.YELLOW}{padded_version}{Style.RESET_ALL} {vertical_char}")

    # Print bottom border
    print(f"{bottom_left}{horizontal_char * (max_content_width + 2)}{bottom_right}")

    parser = argparse.ArgumentParser(
        description="A modern tool to generate requirements.txt for a Python project.",
        epilog="Visit https://github.com/ddt-mmt/pipo for more information."
    )
    parser.add_argument(
        '-v', '--version',
        action='version',
        version=f'%(prog)s {version}'
    )

    subparsers = parser.add_subparsers(dest='command', help='Available commands')
    subparsers.required = True # Make subcommand mandatory
    

    # Scan command, set as default if no subcommand is provided.
    # If a default is needed when no command is provided,
    # the main parser\'s set_defaults(func=...) should be used in conjunction
    # with the subparsers.
    scan_parser = subparsers.add_parser('scan', help='Scan a project and generate requirements.txt')
    scan_parser.add_argument(
        'path',
        nargs='?',
        default='.',
        help='The path to the Python project directory (defaults to the current directory).'
    )
    scan_parser.set_defaults(func=run_scan_command) # Set default function for scan


    # Test command
    test_parser = subparsers.add_parser('test', help='Run tests for the project.')
    test_parser.add_argument(
        'path',
        nargs='?',
        default='.',
        help='The path to the project directory to test (defaults to the current directory).'
    )
    test_parser.set_defaults(func=_run_tests)



    # Uninstall command
    uninstall_parser = subparsers.add_parser('uninstall', help='Uninstall the pipo tool')
    uninstall_parser.set_defaults(func=_uninstall_pipo)


    # Dockerize command
    dockerize_parser = subparsers.add_parser('dockerize', help='Generate a Dockerfile for a Python project')
    dockerize_parser.add_argument(
        'path',
        nargs='?',
        default='.',
        help='The path to the project directory where the Dockerfile will be generated (defaults to current directory).'
    )
    dockerize_parser.add_argument(
        '--app-type',
        default='flask',
        choices=['flask', 'django', 'script'],
        help='Type of Python application (e.g., flask, django, script). Default is flask.'
    )
    dockerize_parser.add_argument(
        '--main-file',
        default='app.py',
        help='The main application file (e.g., app.py, manage.py). Default is app.py.'
    )
    dockerize_parser.add_argument(
        '--port',
        type=int,
        default=5000,
        help='The port your application listens on. Default is 5000.'
    )
    dockerize_parser.set_defaults(func=_dockerize_project) # Set default function for dockerize


    # Init CI command
    init_ci_parser = subparsers.add_parser('init-ci', help='Generate a basic CI/CD configuration file for the project.')
    init_ci_parser.add_argument(
        'path',
        nargs='?',
        default='.',
        help='The path to the project directory where the CI config will be generated (defaults to current directory).'
    )
    init_ci_parser.add_argument(
        '--platform',
        default='github-actions',
        choices=['github-actions'], # Extend this list as more platforms are supported
        help='The CI/CD platform for which to generate the configuration. Default is github-actions.'
    )
    init_ci_parser.add_argument(
        '--docker-image-name',
        default='pipo-app',
        help='The name of the Docker image to build and push (e.g., your_username/your_repo).',
    )
    init_ci_parser.add_argument(
        '--push-docker-image',
        action='store_true',
        help='Set to true to enable pushing the Docker image to a registry.'
    )
    init_ci_parser.set_defaults(func=_init_ci)

    # Kube command
    kube_parser = subparsers.add_parser('kube', help='Generate Kubernetes deployment and service YAML files')
    kube_parser.add_argument(
        'path',
        nargs='?',
        default='.',
        help='The path to the project directory where YAML files will be generated (defaults to current directory).'
    )
    kube_parser.add_argument(
        '-i', '--image',
        help='The Docker image to deploy (e.g., yourname/your-app:v1).',
    )
    kube_parser.add_argument(
        '-a', '--app-name',
        help='The name for the application. Defaults to being derived from the image name.'
    )
    kube_parser.add_argument(
        '-p', '--port',
        type=int,
        help='The port your container exposes. Default is 8080.'
    )
    kube_parser.add_argument(
        '-s', '--service-type',
        choices=['NodePort', 'LoadBalancer', 'ClusterIP'],
        help='The type of Kubernetes service to create. Default is NodePort.'
    )
    kube_parser.add_argument(
        '-n', '--namespace',
        help='The Kubernetes namespace to deploy to. Default is "default".'
    )
    kube_parser.add_argument(
        '-g', '--ingress',
        action='store_true',
        help='Set to generate an Ingress YAML file.'
    )
    kube_parser.add_argument(
        '--host',
        help='The hostname for the Ingress (e.g., myapp.example.com). Required if --ingress is used.'
    )
    kube_parser.add_argument(
        '--path-ingress',
        default='/',
        help='The path for the Ingress (e.g., / or /api). Default is /.'
    )
    kube_parser.add_argument(
        '--ingress-class',
        default='nginx',
        help='The Ingress Class to use (e.g., nginx, traefik). Default is nginx.'
    )
    kube_parser.set_defaults(func=_generate_kube_manifests)

    # Security Scan command
    security_scan_parser = subparsers.add_parser('security-scan', help='Scan requirements.txt for known vulnerabilities using Safety.')
    security_scan_parser.add_argument(
        'path',
        nargs='?',
        default='.',
        help='The path to the Python project directory (defaults to the current directory).'
    )
    security_scan_parser.set_defaults(func=_security_scan)

    # Helm Chart command
    helm_chart_parser = subparsers.add_parser('helm-chart', help='Generate a basic Helm chart structure.')
    helm_chart_parser.add_argument(
        'chart_name',
        help='The name of the Helm chart to create.'
    )
    helm_chart_parser.add_argument(
        'path',
        nargs='?',
        default='.',
        help='The path where the Helm chart will be generated (defaults to current directory).'
    )
    helm_chart_parser.set_defaults(func=_generate_helm_chart)

    # SAST command
    sast_parser = subparsers.add_parser('sast', help='Perform Static Application Security Testing (SAST) using Bandit.')
    sast_parser.add_argument(
        'path',
        nargs='?',
        default='.',
        help='The path to the Python project directory to scan (defaults to current directory).'
    )
    sast_parser.set_defaults(func=_sast_scan)

    # GitOps Manifest command
    gitops_manifest_parser = subparsers.add_parser('gitops-manifest', help='Generate a basic GitOps manifest (e.g., Argo CD Application).')
    gitops_manifest_parser.add_argument(
        'path',
        nargs='?',
        default='.',
        help='The path to the project directory where the GitOps manifest will be generated (defaults to current directory).'
    )
    gitops_manifest_parser.add_argument(
        '--app-name',
        help='The name of the application for the GitOps manifest. Default is derived or prompted.'
    )
    gitops_manifest_parser.add_argument(
        '--repo-url',
        help='The URL of the Git repository containing the Kubernetes manifests.'
    )
    gitops_manifest_parser.add_argument(
        '--path-in-repo',
        default='.',
            help='The path within the repository to the Kubernetes manifests (defaults to \'.\').'
    )
    gitops_manifest_parser.add_argument(
        '--target-revision',
        default='HEAD',
        help='The target Git revision (branch, tag, or commit SHA). Default is HEAD.'
    )
    gitops_manifest_parser.add_argument(
        '--namespace',
        help='The Kubernetes Namespace where the application will be deployed. Default is default.'
    )
    gitops_manifest_parser.add_argument(
        '--tool',
        choices=['argocd', 'fluxcd'],
        help='The GitOps tool to generate manifest for (argocd or fluxcd). Default is argocd.'
    )
    gitops_manifest_parser.set_defaults(func=_generate_gitops_manifest)
    
    args = parser.parse_args()

    try:
        if 'func' in args:
            args.func(args)
        else:
            parser.print_help()
    except subprocess.CalledProcessError as e:
        sys.exit(e.returncode)


if __name__ == "__main__":
    main()
